# JAA: Finish makefile to build tools
PREFIX = 
INCLUDES = 
CCFLAGS = -g -O2  
LIBS = 
TARGETS = abe-setup abe-keygen abe-enc abe-dec

all: $(TARGETS)

abe-setup:

abe-keygen:

abe-enc:

abe-dec:

install:

clean:
	rm $(TARGETS)

%.o: %.c
	$(CC) $(CCFLAGS) -c $<


