Document: libfenc
Title: Debian libfenc Manual
Author: <insert document author here>
Abstract: This manual describes what libfenc is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libfenc/libfenc.sgml.gz

Format: postscript
Files: /usr/share/doc/libfenc/libfenc.ps.gz

Format: text
Files: /usr/share/doc/libfenc/libfenc.text.gz

Format: HTML
Index: /usr/share/doc/libfenc/html/index.html
Files: /usr/share/doc/libfenc/html/*.html
